// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NANDx5 (
B,C,A,D,E,VDD,GND,OUT );
input  B;
input  C;
input  A;
input  D;
input  E;
input  VDD;
input  GND;
output  OUT;
wire VDD;
wire net101;
wire net102;
wire C;
wire A;
wire OUT;
wire net99;
wire GND;
wire E;
wire D;
wire B;
wire net100;

pmos1v    
 PM4  ( .S( VDD ), .G( E ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM3  ( .S( VDD ), .G( D ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM2  ( .S( VDD ), .G( C ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM1  ( .S( VDD ), .G( B ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM0  ( .S( VDD ), .G( A ), .B( VDD ), .D( OUT ) );

nmos1v    
 NM4  ( .S( GND ), .G( E ), .B( GND ), .D( net102 ) );

nmos1v    
 NM3  ( .S( net102 ), .G( D ), .B( GND ), .D( net99 ) );

nmos1v    
 NM1  ( .S( net101 ), .G( B ), .B( GND ), .D( net100 ) );

nmos1v    
 NM2  ( .S( net99 ), .G( C ), .B( GND ), .D( net101 ) );

nmos1v    
 NM0  ( .S( net100 ), .G( A ), .B( GND ), .D( OUT ) );

endmodule

