// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module AND (
GND,VDD,B,A,OUT );
input  GND;
input  VDD;
input  B;
input  A;
output  OUT;
wire VDD;
wire A;
wire B;
wire GND;
wire net08;
wire OUT;

NAND    
 I2  ( .VDD( VDD ), .A( A ), .B( B ), .OUT( net08 ), .GND( GND ) );

INV    
 I1  ( .VDD( VDD ), .Vin( net08 ), .Vout( OUT ), .GND( GND ) );

endmodule

