// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module AND (
VDD,GND,A,B,OUT );
input  VDD;
input  GND;
input  A;
input  B;
output  OUT;
wire VDD;
wire net13;
wire A;
wire OUT;
wire GND;
wire B;

nmos1v    
 NM1  ( .S( GND ), .G( net13 ), .B( GND ), .D( OUT ) );

nmos1v    
 NM0  ( .S( A ), .G( B ), .B( GND ), .D( OUT ) );

pmos1v    
 PM0  ( .S( A ), .G( net13 ), .B( VDD ), .D( OUT ) );

INV    
 I0  ( .VDD( VDD ), .Vin( B ), .Vout( net13 ), .GND( GND ) );

endmodule

