// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module TEST_ABS (
);
wire OUT0;
wire \vdd! ;
wire OUT3;
wire \gnd! ;
wire A1;
wire S0;
wire A0;
wire S4;
wire S3;
wire net056;
wire A2;
wire OUT2;
wire OUT1;
wire A4;
wire S1;
wire OUT4;
wire A3;
wire S2;

INV_5bit    
 I0  ( .Vout2( A2 ), .VDD( \vdd!  ), .Vin4( \vdd!  ), .Vin0( \vdd!  ), .Vin1( \gnd!  ), .Vout1( A1 ), .Vin3( \gnd!  ), .Vout4( A4 ), .Vout0( A0 ), .Vin2( \gnd!  ), .Vout3( A3 ), .GND( \gnd!  ) );

MUX_5bit    
 I3  ( .OUT0( OUT0 ), .VDD( \vdd!  ), .B1( S1 ), .OUT3( OUT3 ), .A1( \gnd!  ), .S( \vdd!  ), .A0( \vdd!  ), .B0( S0 ), .A2( \gnd!  ), .OUT2( OUT2 ), .OUT1( OUT1 ), .B4( S4 ), .B2( S2 ), .A4( \vdd!  ), .OUT4( OUT4 ), .GND( \gnd!  ), .B3( S3 ), .A3( \gnd!  ) );

Adder_5bit    
 I4  ( .Cin( \vdd!  ), .VDD( \vdd!  ), .B1( \gnd!  ), .A1( A1 ), .S0( S0 ), .A0( A0 ), .B0( \gnd!  ), .S4( S4 ), .S3( S3 ), .A2( A2 ), .Cout( net056 ), .B4( \gnd!  ), .B2( \gnd!  ), .A4( A4 ), .S1( S1 ), .GND( \gnd!  ), .B3( \gnd!  ), .A3( A3 ), .S2( S2 ) );

endmodule

