// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module XORx5 (
A0,A1,A2,A3,A4,A5,VDD,GND,OUT0,OUT1,OUT2,OUT3,OUt4 );
input  A0;
input  A1;
input  A2;
input  A3;
input  A4;
input  A5;
input  VDD;
input  GND;
output  OUT0;
output  OUT1;
output  OUT2;
output  OUT3;
output  OUt4;
wire VDD;
wire OUt4;
wire OUT0;
wire OUT3;
wire A1;
wire A0;
wire OUT2;
wire A2;
wire OUT1;
wire A5;
wire A4;
wire GND;
wire A3;

XOR    
 I4  ( .VDD( VDD ), .A( A4 ), .B( A5 ), .OUT( OUt4 ), .GND( GND ) );

XOR    
 I3  ( .VDD( VDD ), .A( A3 ), .B( A5 ), .OUT( OUT3 ), .GND( GND ) );

XOR    
 I2  ( .VDD( VDD ), .A( A2 ), .B( A5 ), .OUT( OUT2 ), .GND( GND ) );

XOR    
 I1  ( .VDD( VDD ), .A( A1 ), .B( A5 ), .OUT( OUT1 ), .GND( GND ) );

XOR    
 I0  ( .VDD( VDD ), .A( A0 ), .B( A5 ), .OUT( OUT0 ), .GND( GND ) );

endmodule

