// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NORx5 (
D,B,A,GND,VDD,C,OUT,E );
input  D;
input  B;
input  A;
input  GND;
input  VDD;
input  C;
output  OUT;
input  E;
wire VDD;
wire net92;
wire C;
wire net95;
wire A;
wire net94;
wire E;
wire GND;
wire D;
wire B;
wire OUT;
wire net93;

nmos1v    
 NM5  ( .S( GND ), .G( E ), .B( GND ), .D( OUT ) );

nmos1v    
 NM2  ( .S( GND ), .G( C ), .B( GND ), .D( OUT ) );

nmos1v    
 NM0  ( .S( GND ), .G( A ), .B( GND ), .D( OUT ) );

nmos1v    
 NM1  ( .S( GND ), .G( B ), .B( GND ), .D( OUT ) );

nmos1v    
 NM3  ( .S( GND ), .G( D ), .B( GND ), .D( OUT ) );

pmos1v    
 PM3  ( .S( VDD ), .G( E ), .B( VDD ), .D( net92 ) );

pmos1v    
 PM2  ( .S( net93 ), .G( C ), .B( VDD ), .D( net95 ) );

pmos1v    
 PM0  ( .S( net95 ), .G( A ), .B( VDD ), .D( net94 ) );

pmos1v    
 PM1  ( .S( net94 ), .G( B ), .B( VDD ), .D( OUT ) );

pmos1v    
 NM4  ( .S( net92 ), .G( D ), .B( VDD ), .D( net93 ) );

endmodule

