// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module ABS_Value_Detector_S (
GND,VDD,T4,T3,T2,T1,T0,X5,X4,X3,X2,X1,X0,OUT );
input  GND;
input  VDD;
input  T4;
input  T3;
input  T2;
input  T1;
input  T0;
input  X5;
input  X4;
input  X3;
input  X2;
input  X1;
input  X0;
output  OUT;
wire VDD;
wire net41;
wire X0;
wire X3;
wire X1;
wire X4;
wire X2;
wire T2;
wire X5;
wire T3;
wire net43;
wire T4;
wire net42;
wire T0;
wire GND;
wire OUT;
wire T1;
wire net45;
wire net44;

ABS_S    
 I0  ( .OUT0( net41 ), .VDD( VDD ), .OUT3( net44 ), .A1( X1 ), .A0( X0 ), .A2( X2 ), .OUT2( net43 ), .OUT1( net42 ), .A5( X5 ), .A4( X4 ), .OUT4( net45 ), .GND( GND ), .A3( X3 ) );

COMPARATOR_S    
 I3  ( .VDD( VDD ), .B1( T1 ), .A1( net42 ), .A0( net41 ), .B0( T0 ), .A2( net43 ), .B4( T4 ), .B2( T2 ), .A4( net45 ), .OUT( OUT ), .GND( GND ), .B3( T3 ), .A3( net44 ) );

endmodule

