// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module ANDx4 (
A,B,C,GND,OUT,D,VDD );
input  A;
input  B;
input  C;
input  GND;
output  OUT;
input  D;
input  VDD;
wire VDD;
wire net036;
wire C;
wire net038;
wire net037;
wire A;
wire net033;
wire B;
wire OUT;
wire GND;
wire D;

INV    
 I3  ( .VDD( VDD ), .Vin( net033 ), .Vout( OUT ), .GND( GND ) );

pmos1v    
 PM3  ( .S( VDD ), .G( D ), .B( VDD ), .D( net033 ) );

pmos1v    
 PM2  ( .S( VDD ), .G( C ), .B( VDD ), .D( net033 ) );

pmos1v    
 PM1  ( .S( VDD ), .G( B ), .B( VDD ), .D( net033 ) );

pmos1v    
 PM0  ( .S( VDD ), .G( A ), .B( VDD ), .D( net033 ) );

nmos1v    
 NM3  ( .S( GND ), .G( D ), .B( GND ), .D( net036 ) );

nmos1v    
 NM2  ( .S( net036 ), .G( C ), .B( GND ), .D( net038 ) );

nmos1v    
 NM0  ( .S( net037 ), .G( A ), .B( GND ), .D( net033 ) );

nmos1v    
 NM1  ( .S( net038 ), .G( B ), .B( GND ), .D( net037 ) );

endmodule

