// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module AND_prev (
B,A,GND,VDD,OUT );
input  B;
input  A;
input  GND;
input  VDD;
output  OUT;
wire net73;
wire net66;
wire net47;
wire VDD;
wire net65;
wire net59;
wire net75;
wire net76;
wire net53;
wire GND;
wire OUT;
wire net77;
wire net55;
wire net78;
wire net50;
wire A;
wire net68;
wire net64;
wire net69;
wire net48;
wire net46;
wire net57;
wire net52;
wire net51;
wire net61;
wire net49;
wire net71;
wire net63;
wire net44;
wire net72;
wire net60;
wire net74;
wire net70;
wire net79;
wire net62;
wire net67;
wire net56;
wire net54;
wire net42;
wire net80;
wire net58;
wire B;
wire net45;

nmos1v    
 NM5  (  );

nmos1v    
 NM4  (  );

nmos1v    
 NM3  (  );

nmos1v    
 NM2  (  );

pmos1v    
 PM3  (  );

pmos1v    
 PM2  (  );

pmos1v    
 PM1  (  );

INV    
 I2  (  );

INV    
 I1  (  );

endmodule

