// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module MUX_1bit (
B,OUT,A,S,VDD,GND );
input  B;
output  OUT;
input  A;
input  S;
input  VDD;
input  GND;
wire VDD;
wire S;
wire net15;
wire A;
wire GND;
wire B;
wire OUT;

pmos1v    
 PM1  ( .S( A ), .G( S ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM0  ( .S( B ), .G( net15 ), .B( VDD ), .D( OUT ) );

nmos1v    
 NM1  ( .S( A ), .G( net15 ), .B( GND ), .D( OUT ) );

nmos1v    
 NM0  ( .S( B ), .G( S ), .B( GND ), .D( OUT ) );

INV    
 I2  ( .VDD( VDD ), .Vin( S ), .Vout( net15 ), .GND( GND ) );

endmodule

