// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module TEST_COMPARATOR (
);
wire \vdd! ;
wire \gnd! ;
wire OUT;

COMPARATOR    
 I0  ( .VDD( \vdd!  ), .B1( \vdd!  ), .A1( \vdd!  ), .A0( \vdd!  ), .B0( \vdd!  ), .A2( \vdd!  ), .B4( \gnd!  ), .B2( \vdd!  ), .A4( \gnd!  ), .OUT( OUT ), .GND( \gnd!  ), .B3( \gnd!  ), .A3( \gnd!  ) );

endmodule

