// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module NANDx4 (
A,B,D,C,VDD,GND,OUT );
input  A;
input  B;
input  D;
input  C;
input  VDD;
input  GND;
output  OUT;
wire VDD;
wire net85;
wire C;
wire net84;
wire A;
wire OUT;
wire net83;
wire D;
wire B;
wire GND;

pmos1v    
 PM3  ( .S( VDD ), .G( D ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM2  ( .S( VDD ), .G( C ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM1  ( .S( VDD ), .G( B ), .B( VDD ), .D( OUT ) );

pmos1v    
 PM0  ( .S( VDD ), .G( A ), .B( VDD ), .D( OUT ) );

nmos1v    
 NM3  ( .S( GND ), .G( D ), .B( GND ), .D( net83 ) );

nmos1v    
 NM2  ( .S( net83 ), .G( C ), .B( GND ), .D( net84 ) );

nmos1v    
 NM0  ( .S( net85 ), .G( A ), .B( GND ), .D( OUT ) );

nmos1v    
 NM1  ( .S( net84 ), .G( B ), .B( GND ), .D( net85 ) );

endmodule

