// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module ABS (
A0,A1,A2,A3,A4,A5,VDD,GND,OUT0,OUT1,OUT2,OUT3,OUT4 );
input  A0;
input  A1;
input  A2;
input  A3;
input  A4;
input  A5;
input  VDD;
input  GND;
output  OUT0;
output  OUT1;
output  OUT2;
output  OUT3;
output  OUT4;
wire VDD;
wire net29;
wire OUT0;
wire OUT3;
wire net31;
wire A1;
wire A0;
wire OUT1;
wire OUT2;
wire A2;
wire A4;
wire OUT4;
wire GND;
wire net27;
wire A5;
wire net28;
wire A3;
wire net30;

INV_5bit    
 I4  ( .Vout2( net28 ), .VDD( VDD ), .Vin4( A4 ), .Vin0( A0 ), .Vin1( A1 ), .Vout1( net29 ), .S( A5 ), .Vin3( A3 ), .Vout4( net27 ), .Vout0( net30 ), .Vin2( A2 ), .Vout3( net31 ), .GND( GND ) );

FAdder_S    
 I3  ( .Cin( A5 ), .VDD( VDD ), .A1( net29 ), .S0( OUT0 ), .A0( net30 ), .S4( OUT4 ), .S3( OUT3 ), .A2( net28 ), .A4( net27 ), .S1( OUT1 ), .GND( GND ), .A3( net31 ), .S2( OUT2 ) );

endmodule

