// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module COMPARATOR_S (
OUT,B4,A3,B3,A2,B2,A1,B1,A0,B0,VDD,GND,A4 );
output  OUT;
input  B4;
input  A3;
input  B3;
input  A2;
input  B2;
input  A1;
input  B1;
input  A0;
input  B0;
input  VDD;
input  GND;
input  A4;
wire VDD;
wire net0113;
wire A0;
wire net0131;
wire net0135;
wire GND;
wire OUT;
wire A3;
wire net0127;
wire B1;
wire A1;
wire net0140;
wire net0144;
wire net0125;
wire net063;
wire net0112;
wire net0117;
wire B2;
wire A4;
wire net0143;
wire net0136;
wire net0115;
wire net0129;
wire net0134;
wire net0114;
wire A2;
wire net0132;
wire net0128;
wire net0141;
wire net0123;
wire B0;
wire net0139;
wire net0138;
wire net0111;
wire net0130;
wire net0142;
wire B4;
wire net0137;
wire net0116;
wire B3;

INV    
 I72  ( .VDD( VDD ), .Vin( net0111 ), .Vout( net063 ), .GND( GND ) );

INV    
 I0  ( .VDD( VDD ), .Vin( B4 ), .Vout( net0143 ), .GND( GND ) );

INV    
 I1  ( .VDD( VDD ), .Vin( A4 ), .Vout( net0142 ), .GND( GND ) );

INV    
 I34  ( .VDD( VDD ), .Vin( A1 ), .Vout( net0136 ), .GND( GND ) );

INV    
 I32  ( .VDD( VDD ), .Vin( B2 ), .Vout( net0139 ), .GND( GND ) );

INV    
 I30  ( .VDD( VDD ), .Vin( A2 ), .Vout( net0138 ), .GND( GND ) );

INV    
 I36  ( .VDD( VDD ), .Vin( B1 ), .Vout( net0137 ), .GND( GND ) );

INV    
 I38  ( .VDD( VDD ), .Vin( A0 ), .Vout( net0135 ), .GND( GND ) );

INV    
 I28  ( .VDD( VDD ), .Vin( B3 ), .Vout( net0141 ), .GND( GND ) );

INV    
 I26  ( .VDD( VDD ), .Vin( A3 ), .Vout( net0140 ), .GND( GND ) );

NAND    
 I67  ( .VDD( VDD ), .A( net0117 ), .B( net0113 ), .OUT( net0132 ), .GND( GND ) );

NOR    
 I66  ( .VDD( VDD ), .A( B1 ), .B( net0136 ), .OUT( net0112 ), .GND( GND ) );

NOR    
 I65  ( .VDD( VDD ), .A( B2 ), .B( net0138 ), .OUT( net0114 ), .GND( GND ) );

NOR    
 I64  ( .VDD( VDD ), .A( B3 ), .B( net0140 ), .OUT( net0113 ), .GND( GND ) );

NOR    
 I63  ( .VDD( VDD ), .A( B4 ), .B( net0142 ), .OUT( net0111 ), .GND( GND ) );

NOR    
 I62  ( .VDD( VDD ), .A( net0135 ), .B( B0 ), .OUT( net0129 ), .GND( GND ) );

NOR    
 I61  ( .VDD( VDD ), .A( A1 ), .B( net0137 ), .OUT( net0123 ), .GND( GND ) );

NOR    
 I60  ( .VDD( VDD ), .A( A2 ), .B( net0139 ), .OUT( net0125 ), .GND( GND ) );

NOR    
 I59  ( .VDD( VDD ), .A( A3 ), .B( net0141 ), .OUT( net0127 ), .GND( GND ) );

NOR    
 I58  ( .VDD( VDD ), .A( A4 ), .B( net0143 ), .OUT( net0128 ), .GND( GND ) );

NOR    
 I43  ( .VDD( VDD ), .A( net0113 ), .B( net0127 ), .OUT( net0116 ), .GND( GND ) );

NOR    
 I42  ( .VDD( VDD ), .A( net0128 ), .B( net0111 ), .OUT( net0117 ), .GND( GND ) );

NOR    
 I44  ( .VDD( VDD ), .A( net0125 ), .B( net0114 ), .OUT( net0115 ), .GND( GND ) );

NOR    
 I45  ( .VDD( VDD ), .A( net0112 ), .B( net0123 ), .OUT( net0130 ), .GND( GND ) );

NANDx3    
 I68  ( .VDD( VDD ), .C( net0114 ), .A( net0117 ), .GND( GND ), .B( net0116 ), .OUT( net0144 ) );

NANDx4    
 I69  ( .VDD( VDD ), .C( net0115 ), .A( net0117 ), .GND( GND ), .D( net0112 ), .B( net0116 ), .OUT( net0131 ) );

NANDx5    
 I71  ( .VDD( VDD ), .C( net0144 ), .A( net063 ), .GND( GND ), .D( net0131 ), .B( net0132 ), .E( net0134 ), .OUT( OUT ) );

NANDx5    
 I70  ( .VDD( VDD ), .C( net0115 ), .A( net0129 ), .GND( GND ), .D( net0116 ), .B( net0130 ), .E( net0117 ), .OUT( net0134 ) );

endmodule

