// Verilog netlist generated by RFSiP netlister
// Cadence Design Systems, Inc.

module TEST_AND (
);
wire \vdd! ;
wire \gnd! ;
wire OUT;

AND    
 I0  ( .VDD( \vdd!  ), .A( \gnd!  ), .B( \gnd!  ), .OUT( OUT ), .GND( \gnd!  ) );

endmodule

